services:
  httpbin:
    image: kennethreitz/httpbin:latest
  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      - chown -R 101:101 /home/envoy/logs
    volumes:
      - logs:/home/envoy/logs:rw
  envoy:
    depends_on:
      - chown
      - httpbin
    image: envoyproxy/envoy:v1.23-latest
    command:
      - -c
      - /conf/envoy-config.yaml
      - --log-level
      - info
      - --component-log-level
      - wasm:debug
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /home/envoy/logs/envoy.log
    volumes:
      - ../build:/build
      - .:/conf
      - logs:/home/envoy/logs:rw
    ports:
      - 8080:80
  envoy-logs:
    depends_on:
    - envoy
    image: alpine:3.16
    command: tail -f /home/envoy/logs/envoy.log
    volumes:
      - logs:/home/envoy/logs:ro
  ftw:
    depends_on:
      - envoy-logs
    build: .
    volumes:
      - logs:/home/envoy/logs:ro

volumes:
  logs:
